force_short_threshold = 0.05
optInFastK_Period = 9
optInSlowK_Period = 3
optInSlowK_MAType = 0
optInSlowD_Period = 3
optInSlowD_MAType = 0
K_high_level = 80
K_low_level  = 20
D_high_level = 80
D_low_level = 20
period = 5
